apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: aws-s3-template
  title: EduArn AWS S3 Bucket Template
  description: EduArn Generate Terraform AWS S3 infrastructure

spec:
  owner: group:default/platform-team
  type: infrastructure

  parameters:
    - title: AWS Infrastructure Details
      required:
        - projectName

      properties:
        projectName:
          type: string
          title: Project Name
          description: Enter project name

        awsRegion:
          type: string
          title: AWS Region
          default: us-east-1

  steps:
    # Generate Terraform files
    - id: fetch-base
      name: Generate Terraform Files
      action: fetch:template
      input:
        url: ./skeleton
        values:
          projectName: ${{ parameters.projectName }}
          awsRegion: ${{ parameters.awsRegion }}

    # Create GitHub Repository
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=eduarnofficial&repo=${{ parameters.projectName }}-infra
        defaultBranch: main
        description: Terraform AWS infrastructure generated by Backstage

    # Register Component in Catalog
    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Open Repository
        url: ${{ steps.publish.output.remoteUrl }}
